import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
export type Locale = "zh-CN" | "en-US";
export type TimeMode = "Asia/Shanghai" | "UTC" | "dual";
const dictionary: Record<string, string> = { Overview: "总览", "Data catalog": "数据目录", Maintenance: "维护任务", Runs: "运行记录", Quality: "质量", Explorer: "数据浏览", Operations: "运维", Capacity: "容量", free: "可用", "Warning threshold": "警告阈值", "Review capacity": "查看容量", Datasets: "数据集", "Runs (24h)": "运行（24小时）", "Failure rate (24h)": "失败率（24小时）", "Open findings": "未处理问题", "Recent runs": "最近运行", "Live activity": "实时活动", "Service health": "服务健康", "System signal": "系统状态", "Needs attention": "需要关注", "Degraded and failed runs": "降级与失败运行", "Run ID": "运行 ID", Dataset: "数据集", Status: "状态", Rows: "行数", Kind: "类型", Scope: "范围", Outcome: "结果", Stage: "阶段", Windows: "窗口数", Manifest: "清单", Findings: "问题数", Created: "创建时间", Actions: "操作", Retry: "重试", Acknowledge: "确认", Timestamp: "时间戳", Open: "开盘", High: "最高", Low: "最低", Close: "收盘", Volume: "成交量", Observation: "观测值", Value: "数值", Release: "发布时间", Frequency: "频率", Units: "单位", "Data explorer": "数据浏览器", "Published data": "已发布数据", Query: "查询", "Provider bars": "提供方 K 线", "Market bars": "市场 K 线", Economic: "经济数据", Provider: "数据提供方", Symbol: "标的", Timeframe: "时间粒度", Recipe: "配方", "Recipe version": "配方版本", "Price basis": "价格基准", Start: "开始", End: "结束", "Page size": "页面大小", Previous: "上一页", Next: "下一页", Coverage: "覆盖范围", "Ready intervals and gaps": "就绪区间与缺口", "Task ID": "任务 ID", Updated: "更新时间", "Recent run": "最近运行", "Recent error": "最近错误", Details: "详情", Pause: "暂停", Enable: "启用", "Task list": "任务列表", "Maintenance tasks": "维护任务", Manual: "手动", "Data maintenance": "数据维护", "Create a maintenance task": "创建维护任务", "Task template": "任务模板", "Template name": "模板名称", "Save template": "保存模板", "Delete template": "删除模板", "Run scope": "运行范围", "Start (UTC)": "开始（UTC）", "End (UTC)": "结束（UTC）", Schedule: "调度", Clear: "清除", "Validate and preview": "验证并预览", "Maintenance task details": "维护任务详情", "Submitted tasks": "已提交任务", "Review before submitting": "提交前检查", "Edit parameters": "编辑参数", "Signed in as": "当前登录用户", "Current password": "当前密码", "New password": "新密码", "Change password": "修改密码", Login: "登录", Logout: "退出", Password: "密码", Username: "用户名", "Unable to load data": "无法加载数据", "Try again": "重试", Cancel: "取消", pass: "通过", failed: "失败", running: "运行中", queued: "排队中", succeeded: "成功", paused: "暂停", ok: "正常", warning: "警告", critical: "临界", checking: "检查中", ready: "就绪", unavailable: "不可用", fresh: "最新", stale: "过期" };
const extraDictionary: Record<string, string> = { "Ledger queue": "账本队列", "Maintenance queue": "维护队列", Queued: "排队中", Running: "运行中", Completed: "已完成", "waiting for the worker": "等待 Worker", "in-flight jobs": "执行中的任务", "finished jobs": "已完成任务" };
function read(key: string) { try { return localStorage.getItem(key); } catch { return null; } }
const Context = createContext({ locale: "zh-CN" as Locale, timeMode: "Asia/Shanghai" as TimeMode, setLocale: (_: Locale) => {}, setTimeMode: (_: TimeMode) => {} });
export function PreferencesProvider({ children }: { children: ReactNode }) { const [locale, setLocale] = useState<Locale>(() => read("mdc.locale") === "en-US" ? "en-US" : "zh-CN"); const [timeMode, setTimeMode] = useState<TimeMode>(() => { const value = read("mdc.timeMode"); return value === "UTC" || value === "dual" ? value : "Asia/Shanghai"; }); useEffect(() => { document.documentElement.lang = locale; try { localStorage.setItem("mdc.locale", locale); localStorage.setItem("mdc.timeMode", timeMode); } catch {} }, [locale, timeMode]); return <Context.Provider value={{ locale, timeMode, setLocale, setTimeMode }}>{children}</Context.Provider>; }
export function usePreferences() { const value = useContext(Context); return { ...value, t: (text: string) => value.locale === "zh-CN" ? dictionary[text] ?? extraDictionary[text] ?? text : text }; }
export function TimeDisplay({ value }: { value?: string | null }) { const { locale, timeMode } = usePreferences(); if (!value) return <>—</>; const date = new Date(value); if (Number.isNaN(date.getTime())) return <>—</>; const format = (zone: "UTC" | "Asia/Shanghai") => `${new Intl.DateTimeFormat(locale, { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23", timeZone: zone }).format(date)} ${zone === "UTC" ? "UTC" : "UTC+8"}`; return <time dateTime={date.toISOString()} title={format("UTC")}>{timeMode === "dual" ? <>{format("Asia/Shanghai")}<br />{format("UTC")}</> : format(timeMode)}</time>; }
