import { usePreferences } from "../preferences";
import { type ColumnDef, flexRender, getCoreRowModel, getSortedRowModel, type SortingState, useReactTable } from "@tanstack/react-table";
import { AlertTriangle, ChevronDown, ChevronUp, X } from "lucide-react";
import { type ReactNode, useState } from "react";

export function PageHeader({ eyebrow, title, actions }: { eyebrow: string; title: string; actions?: ReactNode }) { const { t } = usePreferences(); return <header className="page-header"><div><small>{t(eyebrow)}</small><h1>{t(title)}</h1></div><div className="header-actions">{actions}</div></header>; }
export function PanelHeading({ eyebrow, title, action }: { eyebrow: string; title: string; action?: ReactNode }) { const { t } = usePreferences(); return <div className="panel-heading"><div><small>{t(eyebrow)}</small><h2>{t(title)}</h2></div>{action}</div>; }
export function MetricCard({ label, value, note, tone }: { label: string; value: string; note: string; tone?: "warn" | "bad" }) { const { t } = usePreferences(); return <article className={`metric${tone ? ` metric-${tone}` : ""}`}><span>{t(label)}</span><strong>{value}</strong><small>{t(note)}</small></article>; }
export function StatusBadge({ children, tone }: { children: ReactNode; tone: "good" | "warn" | "bad" | "neutral" }) { const { t } = usePreferences(); return <span className={`status ${tone} ${tone === "good" ? "ok" : ""}`}><i />{typeof children === "string" ? t(children) : children}</span>; }
export function EmptyState({ title, detail }: { title: string; detail?: string }) { const { t } = usePreferences(); return <div className="empty-state"><span>∅</span><b>{t(title)}</b>{detail && <p>{t(detail)}</p>}</div>; }
export function LoadingSkeleton({ rows = 3 }: { rows?: number }) { return <div className="skeleton" aria-label="Loading">{Array.from({ length: rows }, (_, index) => <i key={index} />)}</div>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { const { t } = usePreferences(); return <div className="error-state"><AlertTriangle size={18} /><div><b>{t("Unable to load data")}</b><p>{message}</p></div>{onRetry && <button onClick={onRetry}>{t("Try again")}</button>}</div>; }
export function FilterBar({ children }: { children: ReactNode }) { return <div className="filter-bar">{children}</div>; }
export function DataTable<T>({ data, columns, empty = "No rows found.", onRowClick }: { data: T[]; columns: ColumnDef<T>[]; empty?: string; onRowClick?: (row: T) => void }) {
  const { t } = usePreferences();
  const [sorting, setSorting] = useState<SortingState>([]); const table = useReactTable({ data, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel() });
  if (!data.length) return <EmptyState title={empty} />;
  return <div className="table-scroll"><table><thead>{table.getHeaderGroups().map(group => <tr key={group.id}>{group.headers.map(header => <th key={header.id}>{header.isPlaceholder ? null : <button className="sort-button" onClick={header.column.getToggleSortingHandler()} disabled={!header.column.getCanSort()}>{typeof header.column.columnDef.header === "string" ? t(header.column.columnDef.header) : flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() === "asc" ? <ChevronUp size={13} /> : header.column.getIsSorted() === "desc" ? <ChevronDown size={13} /> : null}</button>}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id} className={onRowClick ? "selectable-row" : ""} onClick={() => onRowClick?.(row.original)}>{row.getVisibleCells().map(cell => <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div>;
}
export function DetailDrawer({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <><button className="drawer-scrim" aria-label="Close details" onClick={onClose} /><aside className="detail-drawer" aria-label={title}><header><div><small>Details</small><h2>{title}</h2></div><button className="icon-button" aria-label="Close details" title="Close details" onClick={onClose}><X size={18} /></button></header>{children}</aside></>; }
export function ConfirmDialog({ title, detail, confirmLabel, busy, onConfirm, onCancel }: { title: string; detail: string; confirmLabel: string; busy?: boolean; onConfirm: () => void; onCancel: () => void }) { return <div className="dialog-scrim"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-label={title}><AlertTriangle size={22} /><h2>{title}</h2><p>{detail}</p><div><button className="secondary-button" onClick={onCancel} disabled={busy}>Cancel</button><button className="primary-button" onClick={onConfirm} disabled={busy}>{busy ? "Working…" : confirmLabel}</button></div></div></div>; }

export function CopyId({ value }: { value: string }) {
 const { locale } = usePreferences(); const [copied, setCopied] = useState(false); const [failed, setFailed] = useState(false);
 return <span className="copy-id"><span className="mono" title={value}>{value}</span><button type="button" aria-label={locale === "zh-CN" ? "复制 ID" : "Copy ID"} onClick={async event => { event.stopPropagation(); try { await navigator.clipboard.writeText(value); setCopied(true); setFailed(false); } catch { setFailed(true); } }}>{copied ? "✓" : locale === "zh-CN" ? "复制" : "Copy"}</button>{failed && <small role="status">{locale === "zh-CN" ? "复制不可用，请选择 ID 后复制" : "Select the ID to copy manually"}</small>}</span>;
}
