import { useMemo, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { DataTable, DetailDrawer, FilterBar, LoadingSkeleton, PanelHeading, StatusBadge } from "../components/ui";
import type { Dataset } from "../lib/api";

export function CatalogPage({ datasets, loading, onExplore }: { datasets: Dataset[]; loading: boolean; onExplore: (dataset: Dataset) => void }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Dataset | null>(null); const filtered = useMemo(() => datasets.filter(item => `${item.dataset_id} ${item.description} ${item.schema_version}`.toLowerCase().includes(query.toLowerCase())), [datasets, query]);
  const columns: ColumnDef<Dataset>[] = [{ accessorKey: "dataset_id", header: "Dataset", cell: info => <b>{String(info.getValue())}</b> }, { accessorKey: "schema_version", header: "Schema", cell: info => <StatusBadge tone="neutral">{String(info.getValue())}</StatusBadge> }, { accessorKey: "description", header: "Description" }, { id: "partitions", header: "Partitioning", cell: ({ row }) => row.original.partitioning.join(" / ") }, { id: "coverage", header: "Provider / coverage", enableSorting: false, cell: ({ row }) => <button className="table-action" onClick={event => { event.stopPropagation(); onExplore(row.original); }}>Open Explorer</button> }];
  return <section className="panel"><PanelHeading eyebrow="Registry" title="Data catalog" /><FilterBar><label>Search datasets<input aria-label="Search datasets" value={query} onChange={event => setQuery(event.target.value)} placeholder="Dataset, schema, description" /></label><span>{filtered.length} datasets</span></FilterBar>{loading ? <LoadingSkeleton rows={4} /> : <DataTable data={filtered} columns={columns} empty="No matching datasets." onRowClick={setSelected} />}{selected && <DetailDrawer title={selected.dataset_id} onClose={() => setSelected(null)}><DetailList values={{ "Schema version": selected.schema_version, Description: selected.description, Partitioning: selected.partitioning.join(" / ") }} /><button className="primary-button drawer-action" onClick={() => onExplore(selected)}>Browse provider coverage</button></DetailDrawer>}</section>;
}
function DetailList({ values }: { values: Record<string, string> }) { return <dl className="detail-list">{Object.entries(values).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>; }
