import type { Dataset, Finding, Metrics, ReadyState, Run } from "../lib/api";
import { DataTable, EmptyState, LoadingSkeleton, MetricCard, PanelHeading, StatusBadge } from "../components/ui";
import type { ColumnDef } from "@tanstack/react-table";

const runColumns: ColumnDef<Run>[] = [
  { accessorKey: "run_id", header: "Run ID", cell: info => <span className="mono">{String(info.getValue())}</span> },
  { accessorKey: "dataset_id", header: "Dataset" },
  { accessorKey: "status", header: "Status", cell: info => <StatusBadge tone={tone(String(info.getValue()))}>{String(info.getValue())}</StatusBadge> },
  { accessorKey: "row_count", header: "Rows", cell: info => String(info.getValue() ?? "—") },
];
const tone = (status: string) => status === "pass" || status === "ready" ? "good" as const : status === "failed" || status === "dead_letter" || status === "critical" ? "bad" as const : "warn" as const;

export function OverviewPage({ datasets, runs, findings, health, metrics, loading, onRuns, onOperations }: { datasets: Dataset[]; runs: Run[]; findings: Finding[]; health: ReadyState | null; metrics: Metrics | null; loading: boolean; onRuns: () => void; onOperations: () => void }) {
  const capacity = metrics?.capacity; const day = metrics?.production_sli?.["24h"]; const failureRate = day?.success_rate == null ? null : 1 - day.success_rate;
  return <><div className={`capacity-banner ${health?.capacity_status === "critical" ? "critical" : ""}`}><StatusBadge tone={tone(health?.capacity_status ?? "warning")}>Capacity {health?.capacity_status ?? "checking"}</StatusBadge><span>{capacity ? `${(capacity.free_ratio * 100).toFixed(1)}% free. Warning threshold ${(capacity.warning_free_ratio * 100).toFixed(0)}%.` : "Capacity policy is monitored continuously."}</span><button onClick={onOperations}>Review capacity →</button></div><section className="metrics"><MetricCard label="Datasets" value={loading ? "—" : String(datasets.length)} note="published schemas" /><MetricCard label="Runs (24h)" value={loading ? "—" : String(day?.runs ?? 0)} note={`queue depth ${metrics?.queue_depth ?? 0}`} /><MetricCard label="Failure rate (24h)" value={failureRate == null ? "—" : `${(failureRate * 100).toFixed(1)}%`} note="production terminal runs" tone={failureRate && failureRate > 0 ? "warn" : undefined} /><MetricCard label="Open findings" value={loading ? "—" : String(findings.length)} note={findings.length ? "review required" : "no persisted findings"} /></section><div className="overview-grid"><section className="panel"><PanelHeading eyebrow="Live activity" title="Recent runs" action={<button className="link-button" onClick={onRuns}>View all →</button>} />{loading ? <LoadingSkeleton rows={4} /> : runs.length ? <DataTable data={runs.slice(0, 5)} columns={runColumns} /> : <EmptyState title="No runs recorded" detail="Queued ingest and retry activity will appear here." />}</section><section className="panel health-panel"><PanelHeading eyebrow="System signal" title="Service health" action={<StatusBadge tone={tone(health?.status ?? "checking")}>{health?.status ?? "Checking"}</StatusBadge>} /><div className="health-score"><strong>{health?.status === "ready" ? "Ready" : "—"}</strong><span>operational snapshot {health?.operational_snapshot_status ?? "unknown"}</span></div><dl><div><dt>Read path</dt><dd>{health?.read_status ?? "—"}</dd></div><div><dt>Write path</dt><dd>{health?.write_status ?? "—"}</dd></div><div><dt>Worker heartbeat</dt><dd>{health?.worker_heartbeat_age_seconds == null ? "—" : `${Math.round(health.worker_heartbeat_age_seconds)}s`}</dd></div><div><dt>Deployment</dt><dd className="mono">{health?.deployment_id ?? "—"}</dd></div></dl></section></div></>;
}
