import { useMemo, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { DataTable, DetailDrawer, FilterBar, PanelHeading, StatusBadge } from "../components/ui";
import type { Finding } from "../lib/api";

export function QualityPage({ findings }: { findings: Finding[] }) {
  const [severity, setSeverity] = useState("all"); const [code, setCode] = useState("all"); const [dataset, setDataset] = useState("all"); const [from, setFrom] = useState(""); const [through, setThrough] = useState(""); const [selected, setSelected] = useState<Finding | null>(null); const datasets = [...new Set(findings.map(item => item.dataset_id).filter(Boolean))] as string[]; const codes = [...new Set(findings.map(item => item.code))]; const filtered = useMemo(() => findings.filter(item => { const timestamp = (item.observation_date || item.bar_ts || "").slice(0, 10); return (severity === "all" || item.severity === severity) && (code === "all" || item.code === code) && (dataset === "all" || item.dataset_id === dataset) && (!from || timestamp >= from) && (!through || timestamp <= through); }), [findings, severity, code, dataset, from, through]);
  const columns: ColumnDef<Finding>[] = [{ accessorKey: "severity", header: "Severity", cell: info => <StatusBadge tone={String(info.getValue()) === "error" || String(info.getValue()) === "high" ? "bad" : "warn"}>{String(info.getValue())}</StatusBadge> }, { accessorKey: "code", header: "Code" }, { accessorKey: "dataset_id", header: "Dataset", cell: info => String(info.getValue() ?? "—") }, { id: "timestamp", header: "Timestamp", cell: ({ row }) => row.original.observation_date || row.original.bar_ts || "—" }];
  return <section className="panel"><PanelHeading eyebrow="System signal" title="Quality findings" /><FilterBar><label>Severity<select aria-label="Severity" value={severity} onChange={event => setSeverity(event.target.value)}><option>all</option>{[...new Set(findings.map(item => item.severity))].map(value => <option key={value}>{value}</option>)}</select></label><label>Code<select aria-label="Finding code" value={code} onChange={event => setCode(event.target.value)}><option>all</option>{codes.map(value => <option key={value}>{value}</option>)}</select></label><label>Dataset<select aria-label="Quality dataset" value={dataset} onChange={event => setDataset(event.target.value)}><option>all</option>{datasets.map(value => <option key={value}>{value}</option>)}</select></label><label>From<input aria-label="Finding from date" type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>Through<input aria-label="Finding through date" type="date" value={through} onChange={event => setThrough(event.target.value)} /></label><span>{filtered.length} findings</span></FilterBar><DataTable data={filtered} columns={columns} empty="No quality findings." onRowClick={setSelected} />{selected && <DetailDrawer title={selected.code} onClose={() => setSelected(null)}><dl className="detail-list">{Object.entries(selected).map(([key, value]) => value != null && <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></DetailDrawer>}</section>;
}
