import { useEffect, useMemo, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { ConfirmDialog, DataTable, DetailDrawer, ErrorState, FilterBar, LoadingSkeleton, PanelHeading, StatusBadge } from "../components/ui";
import { createDataCenterClient, type Run } from "../lib/api";

const tone = (status: string) => status === "pass" ? "good" as const : ["failed", "dead_letter"].includes(status) ? "bad" as const : "warn" as const;
export function RunsPage({ apiKey, refreshToken, onChanged, onMessage }: { apiKey: string; refreshToken: number; onChanged: () => void; onMessage: (message: string) => void }) {
  const [status, setStatus] = useState("all"); const [query, setQuery] = useState(""); const [runs, setRuns] = useState<Run[]>([]); const [selected, setSelected] = useState<Run | null>(null); const [pending, setPending] = useState<{ action: "retry" | "acknowledge"; run: Run } | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setRuns((await createDataCenterClient(apiKey).runs(status)).data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load runs"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [status, refreshToken]);
  const filtered = useMemo(() => runs.filter(run => `${run.run_id} ${run.dataset_id} ${run.provider ?? ""} ${run.symbol ?? ""}`.toLowerCase().includes(query.toLowerCase())), [runs, query]);
  const act = async () => { if (!pending) return; setBusy(true); try { if (pending.action === "retry") { const result = await createDataCenterClient(apiKey).retry(pending.run.run_id); onMessage(`Queued retry ${result.data.run_id}`); } else { await createDataCenterClient(apiKey).acknowledge(pending.run.run_id); onMessage(`Acknowledged ${pending.run.run_id}`); } setPending(null); await load(); onChanged(); } catch (reason) { onMessage(reason instanceof Error ? reason.message : "Operation failed"); } finally { setBusy(false); } };
  const columns: ColumnDef<Run>[] = [{ accessorKey: "run_id", header: "Run ID", cell: info => <span className="mono">{String(info.getValue())}</span> }, { accessorKey: "dataset_id", header: "Dataset" }, { accessorKey: "status", header: "Status", cell: info => <StatusBadge tone={tone(String(info.getValue()))}>{String(info.getValue())}</StatusBadge> }, { accessorKey: "row_count", header: "Rows", cell: info => String(info.getValue() ?? "—") }, { accessorKey: "created_at", header: "Created", cell: info => formatTime(String(info.getValue() ?? "")) }, { id: "actions", header: "Actions", enableSorting: false, cell: ({ row }) => <div className="row-actions">{["failed", "dead_letter"].includes(row.original.status) && <button onClick={event => { event.stopPropagation(); setPending({ action: "retry", run: row.original }); }}>Retry</button>}{row.original.status === "dead_letter" && row.original.dead_letter_state?.state !== "acknowledged" && <button onClick={event => { event.stopPropagation(); setPending({ action: "acknowledge", run: row.original }); }}>Acknowledge</button>}</div> }];
  return <section className="panel"><PanelHeading eyebrow="Live activity" title="Ingest runs" action={<button className="link-button" onClick={() => void load()}>Refresh →</button>} /><FilterBar><label>Status<select aria-label="Status" value={status} onChange={event => setStatus(event.target.value)}>{["all", "queued", "running", "pass", "failed", "dead_letter"].map(value => <option key={value}>{value}</option>)}</select></label><label>Search<input aria-label="Search runs" value={query} onChange={event => setQuery(event.target.value)} placeholder="Run ID, dataset, provider" /></label><span>{filtered.length} runs</span></FilterBar>{loading ? <LoadingSkeleton rows={5} /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : <DataTable data={filtered} columns={columns} empty="No matching runs." onRowClick={setSelected} />}{selected && <DetailDrawer title={selected.run_id} onClose={() => setSelected(null)}><StatusBadge tone={tone(selected.status)}>{selected.status}</StatusBadge><dl className="detail-list">{Object.entries(selected).filter(([, value]) => value != null && typeof value !== "object").map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></DetailDrawer>}{pending && <ConfirmDialog title={pending.action === "retry" ? "Retry failed run?" : "Acknowledge dead letter?"} detail={pending.action === "retry" ? "A new run will be queued. The original terminal run remains immutable." : "This records an additive acknowledgement and does not modify the terminal run."} confirmLabel={pending.action === "retry" ? "Queue retry" : "Acknowledge"} busy={busy} onConfirm={() => void act()} onCancel={() => setPending(null)} />}</section>;
}
const formatTime = (value: string) => value ? new Date(value).toLocaleString("en-GB", { timeZone: "UTC", hour12: false }) : "—";
